[package]
name = "mdbook-rfc-summaries"
version = "0.1.0"
edition = "2024"

[dependencies]
mdbook = { version = "0.4.44", default-features = false }
pulldown-cmark = "0.12.2"
pulldown-cmark-to-cmark = "20.0.0"
serde = "1.0.217"
serde_json = "1.0.138"
